apiVersion: apps/v1
kind: Deployment
metadata:
  name: green-app
  labels:
    app: blue-green-app
    color: green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: blue-green-app
      color: green
  template:
    metadata:
      labels:
        app: blue-green-app
        color: green
    spec:
      containers:
      - name: app-container
        image: nginx:1.22
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "128Mi"
            cpu: "250m"

