apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue-app
  labels:
    app: blue-green-app
    color: blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: blue-green-app
      color: blue
  template:
    metadata:
      labels:
        app: blue-green-app
        color: blue
    spec:
      containers:
      - name: app-container
        image: nginx:1.21
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "128Mi"
            cpu: "250m"

